export const products = [
  {
    "id": 1,
    "category": "camiseta",
    "title": "Camiseta OverSixe",
    "description": "",
    "img": "https://i.pinimg.com/originals/60/de/0a/60de0a084a7490cf91ba6ddae0e070c7.jpg",
    "size": [
      "S",
      "M",
      "L",
      "XL",
    ],
    "price": 45000,
    "outstanding": "",
    "discount": "",
    "Stock": 12,
  },
  {
    "id": 2,
    "category": "camiseta",
    "title": "Camiseta Altervative",
    "description": "",
    "img": "https://i.pinimg.com/originals/60/de/0a/60de0a084a7490cf91ba6ddae0e070c7.jpg",
    "size": [
      "S",
      "M",
      "L",
      "XL",
    ],
    "price": 45000,
    "outstanding": "",
    "discount": "",
    "Stock": 12,
  },
  {
    "id": 3,
    "category": "camiseta",
    "title": "Camiseta colorFull",
    "description": "",
    "img": "https://i.pinimg.com/originals/60/de/0a/60de0a084a7490cf91ba6ddae0e070c7.jpg",
    "size": [
      "S",
      "M",
      "L",
      "XL",
    ],
    "price": 45000,
    "outstanding": "",
    "discount": "",
    "Stock": 12,
  },
  {
    "id": 4,
    "category": "camiseta",
    "title": "Camiseta Hardcore",
    "description": "",
    "img": "https://i.pinimg.com/originals/60/de/0a/60de0a084a7490cf91ba6ddae0e070c7.jpg",
    "size": [
      "S",
      "M",
      "L",
      "XL",
    ],
    "price": 45000,
    "outstanding": "",
    "discount": "",
    "Stock": 12,
  }
]